tesis/config/routes.rb
Rails.application.routes.draw do
  resources :rdas
#  resources :pregunta
  resources :programas
  resources :propositos
  resources :rda_generals
 

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

tesis/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

tesis/app/models/programa.rb
class Programa < ApplicationRecord
	#has_many :preguntas, class_name: "Preguntum"
	#has_many :has_unity
	#has_many :untiies, through: :has_unity
	has_one :rda_general
	#after_create 	:set_has_rda
	#Asignación del atributo virtual rda (Para cuando se crea)


end

tesis/app/models/proposito.rb
class Proposito < ApplicationRecord
	has_and_belongs_to_many :Rdas
end

tesis/app/models/propositos_rda.rb
class PropositosRda < ApplicationRecord
  belongs_to :rdas
  belongs_to :propositos
end

tesis/app/models/rda.rb
class Rda < ApplicationRecord
  has_and_belongs_to_many :Propositos
end

tesis/app/models/rda_general.rb
class RdaGeneral < ApplicationRecord
	has_many :Unitys
end

tesis/app/models/unity.rb
class Unity < ApplicationRecord
  belongs_to :RdaGenerals
  belongs_to :Rdas
end

tesis/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

tesis/app/controllers/programas_controller.rb
class ProgramasController < ApplicationController
  before_action :set_programa, only: [:show, :edit, :update, :destroy]

  # GET /programas
  # GET /programas.json
  def index
    @programas = Programa.all
  end

  # GET /programas/1
  # GET /programas/1.json
  def show
  end

  # GET /programas/new
  def new
    @programa = Programa.new
    @rda = RdaGeneral.new
    @programas = Programa.all
  end

#Funcion Insertar una nueva unidad  (Unity)
#  def create_unity 
#    nombre = params[:nombre]
#    descripcion = params[:descripcion]
#    @id_rda = params[:rdas]
#    insercion1 = Unity.create(descripcion: descripcion, nombre: nombre, id_rda: @id_rda.join(" "))
#    puts insercion1 
#    redirect_to action: 'new'
#  end
    #@unidad = Unity.new(params[:descripcion],)
  #Validaciones respecto a los parametros de unidad 
#    if params[:descripcion].nil?
#      puts "Entre a que la descripcion esta vacia"
#      flash[:notice] = "Debe ingresar una descripcion"
#      redirect_to action: :new_unity
 #   end
#    if params[:nombre].nil?
#      puts "Entre a el nombre vacio "
#      flash[:notice] = "Debe ingresar un nombre"
#      redirect_to action: :new_unity
#    end
  

  # GET /programas/1/edit
  def edit
#    @rda = ResultadosDeAprendizaje.all
  end

  # POST /programas
  # POST /programas.json
  def create
    puts "AAAAAAAAAAAAAAAAAAHHHHHHHHHHHHHHHHHHHHHHHH"
    puts params[:descripcionNewRda]
    @programa = Programa.new(programa_params)
    respond_to do |format|
      if @programa.save
        format.html { redirect_to @programa, notice: 'Programa fue existosamente creado.' }
        format.json { render :show, status: :created, location: @programa }
        @rdaGeneral = RdaGeneral.new
        @rdaGeneral.descripcion = params[:descripcionNewRda]
        @rdaGeneral.programas_id = @programa.id
      else
        format.html { render :new }
        format.json { render json: @programa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programas/1
  # PATCH/PUT /programas/1.json
  def update
    respond_to do |format|
      if @programa.update(programa_params)
        format.html { redirect_to @programa, notice: 'Programa fue exitosamente actualizado' }
        format.json { render :show, status: :ok, location: @programa }
      else
        format.html { render :edit }
        format.json { render json: @programa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programas/1
  # DELETE /programas/1.json
  def destroy
    @programa.destroy
    puts "pase el destroy"
    respond_to do |format|
      format.html { redirect_to programas_url, notice: 'Programa fue exitosamente eliminado' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_programa
      @programa = Programa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def programa_params
      params.require(:programa).permit(:nombre,:version,:descripcion)
    end 
end

tesis/app/controllers/propositos_controller.rb
class PropositosController < ApplicationController
end

tesis/app/controllers/rda_generals_controller.rb
class RdaGeneralsController < ApplicationController
end

tesis/app/controllers/rdas_controller.rb
class RdasController < ApplicationController

  # GET /rdas
  # GET /rdas.json
  def index
    @rdas = Rda.all
  end

  # GET /resultados_de_aprendizajes/1
  # GET /resultados_de_aprendizajes/1.json
  def show
  	puts "Entré a shoow"
  	@rda = Rda.find(params[:id])
  	@programas = Programa.all
  	@flag = 1 # Para marcar una diferencia entre quien invoca al form_html
  end

  # GET /resultados_de_aprendizajes/new
  def new
    @rda = Rda.new
    @programas = Programa.all
  end

  # GET /resultados_de_aprendizajes/1/edit
  def edit
  	@rda = Rda.find(params[:id])
  	@programas = Programa.all
  end

  # POST /resultados_de_aprendizajes
  # POST /resultados_de_aprendizajes.json
  def create
    @rda = Rda.new(rda_params)
    respond_to do |format|
      if @rda.save
        format.html { redirect_to @rda, notice: 'Resultados de aprendizaje fue creado existosamente' }
        format.json { render :show, status: :created, location: @rda}
      else
        format.html { render :new }
        format.json { render json: @rda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resultados_de_aprendizajes/1
  # PATCH/PUT /resultados_de_aprendizajes/1.json
  def update
    respond_to do |format|
	  @rda = Rda.find(params[:id])
      if @rda.update(rda_params)
        format.html { redirect_to @rda, notice: 'Resultados de aprendizaje exitosamente actualizado' }
        format.json { render :show, status: :ok, location: @rda }
      else
        format.html { render :edit }
        format.json { render json: @rda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resultados_de_aprendizajes/1
  # DELETE /resultados_de_aprendizajes/1.json
  def destroy
    @rda.destroy
    respond_to do |format|
      format.html { redirect_to rdas_url, notice: 'Resultados de aprendizaje fueron exitosamente eliminados' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rda
      @rda = Rda.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rda_params
      params.require(:rda).permit(:descripcion,:programa_id)
    end
end

tesis/app/controllers/unitys_controller.rb
class UnitysController < ApplicationController
end

tesis/app/helpers/application_helper.rb
module ApplicationHelper
end

tesis/app/helpers/programas_helper.rb
module ProgramasHelper
end

tesis/app/helpers/propositos_helper.rb
module PropositosHelper
end

tesis/app/helpers/rda_generals_helper.rb
module RdaGeneralsHelper
end

tesis/app/helpers/rdas_helper.rb
module RdasHelper
end

tesis/app/helpers/unitys_helper.rb
module UnitysHelper
end

tesis/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Tesis - Quiebre activo</title>
  <!-- Bootstrap core CSS-->
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body class="fixed-nav sticky-footer bg-dark" id="page-top">
  <!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand" href="index.html">Quiebre activo</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
          <a class="nav-link" href="/programas">
            <i class="fa fa-fw fa-graduation-cap"></i>
            <span class="nav-link-text">Programa</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables">
          <a class="nav-link" href="</pregunta">
            <i class="fa fa-fw fa-question-circle"></i>
            <span class="nav-link-text">Preguntas</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables">
         <a class="nav-link" href=" /rdas">
            <i class="fa fa-fw fa-list-ol"></i>
            <span class="nav-link-text">Resultados de aprendizaje</span>
          </a>
        </li>

        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables">
          <a class="nav-link" href="/evaluacion">
            <i class="fa fa-fw fa-file-text-o "></i>
            <span class="nav-link-text">Realizar Quiz</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link">
          <a class="nav-link" href="#">
            <i class="fa fa-fw fa-link"></i>
            <span class="nav-link-text">Link</span>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav sidenav-toggler">
        <li class="nav-item">
          <a class="nav-link text-center" id="sidenavToggler">
            <i class="fa fa-fw fa-angle-left"></i>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle mr-lg-2" id="alertsDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-check-square-o"></i>
            <span class="d-lg-none">Alerts
              <span class="badge badge-pill badge-warning">6 New</span>
            </span>
            <span class="indicator text-warning d-none d-lg-block">
              <i class="fa fa-fw fa-circle"></i>
            </span>
          </a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
            <i class="fa fa-fw fa-sign-out"></i>Logout</a>
        </li>
      </ul>
    </div>
  </nav>
  <div class="content-wrapper">
    <div class="container-fluid">
      
    <%= yield %>
    </div>
    <!-- /.container-fluid-->
    <!-- /.content-wrapper-->
    <footer class="sticky-footer">
      <div class="container">
        <div class="text-center">
          <small>Copyright © Benjamín Pastene 2017</small>
        </div>
      </div>
    </footer>
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fa fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <a class="btn btn-primary" href="login.html">Logout</a>
          </div>
        </div>
      </div>
    </div>
    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    
    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>
    <!-- Page level plugin JavaScript-->
    <!-- Custom scripts for all pages-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
  </div>
</body>

</html>

tesis/app/views/programas/_form.html.erb
<%= form_for(programa) do |f| %>
  <% if programa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(programa.errors.count, "error") %> prohibited this programa from being saved:</h2>

      <ul>
      <% programa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :version %>
    <%= f.text_field :version %>
  </div>
  <div class="field">
    <% rdas = RdaGeneral.all %>
    <% rdas.each do |rda| %>
        <%= check_box_tag rda.id %> <%= rda.descripcion %>
        <br>
    <%end%>  
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

tesis/app/views/programas/edit.html.erb
<h1>Editando Programa</h1>

<%= render 'form', programa: @programa %>

<%= link_to 'Mostrar', @programa %> |
<%= link_to 'Volver', programas_path %>

tesis/app/views/programas/index.html.erb
<p id="notice"><%= notice %></p>

<br>

<div class="row">
   <div class="col-lg-12">
      <!-- Example Bar Chart Card-->
      <div class="card mb-3">
         <div class="card-header">
            <i class="fa fa-graduation-cap"></i> Programa
         </div>
         <div class="card-body">
            <div class="row">
               <div class="col-sm-12 my-auto">
                  <table class="table" >
                    <thead>
                      <tr>
                        <th>Nombre</th>
                        <th>Version</th>
                        <th>RDA general</th>
                        <th colspan="3"></th>
                      </tr>
                    </thead>

                    <tbody>
                      <% @programas.each do |programa| %>
                        <tr>
                          <td><%= programa.nombre %></td>
                          <td><%= programa.version %></td>
                          <td> 
                            <% rdas = RdaGeneral.where(programas_id: programa.id).take(10) %>
                            <% if rdas.nil? %>
                              No posee rda asociados
                            <% else %>
                              <% rdas.each do |rda| %>
                                <%= rda.id %>
                              <%end%>
                            <%end%>

                          </td> 
                          <td><%= link_to 'Mostrar', programa %></td>
                          <td><%= link_to 'Editar', edit_programa_path(programa) %></td>
                          <td><%= link_to 'Eliminar', programa, method: :delete, data: { confirm: 'Está seguro que desea eliminar el programa indicado?' } %></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>

            </div>
         </div>
      </div>
   </div>
</div>

<%= link_to 'Agregar Programa', new_programa_path %>

tesis/app/views/programas/new.html.erb
<script>
   $('document').ready(function(){

    $('#myModal').on('shown.bs.modal', function () {
      $('#myInput').trigger('focus')
    })
   });
   function mostrarCaja(){
      console.log("entre a mostrar caja")
      console.log("Entre al if?")
      document.getElementById("descripcionNewRda").style.visibility = 'visible'  
      document.getElementById("labelDescripcionNewRda").style.visibility = 'visible';
      };
</script>


<h1>Agregar programa</h1>
<%= form_for(@programa) do |f| %>
  <% if @programa.errors.any? %>
  <div id="error_explanation">
     <h2><%= pluralize(programa.errors.count, "error") %> prohibited this programa from being saved:</h2>
     <ul>
        <% programa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
     </ul>
  </div>
  <% end %>
  <div class="field">
     <%= f.label :nombre %>
     <%= f.text_field :nombre %>
  </div>
  <div class="field">
     <%= f.label :version %>
     <%= f.text_field :version %>
  </div>
  <div class="field">
     <% rdas = RdaGeneral.all %>
     <% rdas.each do |rda| %>
      <%= check_box_tag rda.id %> <%= rda.descripcion %>
  <br>
  <%end%>  
  </div>
  
  <input type="text" id="descripcionNewRda" name="descripcionNewRda" style="visibility:hidden"/ >
  <br>
  <button type="button" class="btn btn-info" data-toggle="modal" data-target="#exampleModal" onclick="mostrarCaja()">
  Crear rda general
  </button>
  <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#exampleModal" >
  Utilizar rda general ya existente
  </button>


  <div class="actions">
     <%= f.submit %>
  </div>
<% end %>
<br>
<%= link_to 'Volver', programas_path, :class => "btn btn-danger" %>
<!-- Modal para crear un Rda -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
   <div class="modal-dialog" role="document">
      <div class="modal-content">
         <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
         </div>
         <div class="modal-body">
            ...
         </div>
         <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
         </div>
      </div>
   </div>
</div>

tesis/app/views/programas/new_unity.html.erb
<h4> Agregar una unidad </h4>
<%= form_tag(controller: "programas", action: "create_unity", method: "post") do  %> 

  <div class="field">
    <p>Descripcion </p>
    <%= text_field_tag :descripcion %>
  </div>

   <div class="field">
    <p> Nombre </p>
    <%= text_field_tag :nombre %>
  </div>

  <div class="field">
    <p> RDA(s) </p>
    <% @rda.each do |rda| %>
      <div class="field">
        <%= check_box_tag "rdas[]", rda.id %> <%= rda.descripcion_resultado %>
	<%end%>
<br>
 <%= submit_tag "Crear Unidad"%>

<%end%>

tesis/app/views/programas/show.html.erb
  <p id="notice"><%= notice %></p>

<h1> Programa: </h1>


<p>
  <strong>Nombre:</strong>
  <%= @programa.nombre %>
</p>

<p>
  <strong>Version:</strong>
  <%= @programa.version %>	
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @programa.descripcion %>	
</p>



<%= link_to 'Editar', edit_programa_path(@programa) %> |
<%= link_to 'Volver', programas_path %>

tesis/app/views/rdas/_form.html.erb
<div class="form-group">
  <%= form_for(rda) do |f| %>
    <% if rda.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(rda.errors.count, "error") %> prohibited this rda from being saved:</h2>

        <ul>
        <% rda.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :descripcion %>
      <br><br>
      <%= f.text_area :descripcion%>
    </div>

    <!-- Falta agregar que cuando venga de editar se carga el select en el programa ya seleccionado -->
    
      <div class="field">
      <% puts params %>
      <%= f.select(:programa_id) do %>
        <% @programas.each do |c| %>
          <%= content_tag(:option, c.nombre, value: c.id) %>
        <% end %>
      <% end %>
    </div>


    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

tesis/app/views/rdas/edit.html.erb
<h3>Editando resultados de aprendizaje</h3>

<%= form_for @rda, :url => {:action => "update"} do |f| %>

  <div class="form-group">
    <div class="font-italic"> Descripción </div>
    <%= f.text_area :descripcion, :class => "form-control" %>
  </div>

  <!-- Falta agregar que cuando venga de editar se carga el select en el programa ya seleccionado -->
  
    <div class="field">
    
    <%= f.select(:programa_id) do %>
      <% @programas.each do |c| %>
        <%= content_tag(:option, c.nombre, value: c.id) %>
      <% end %>
    <% end %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', @rda %> 
<%= link_to 'Back', rdas_path %>

tesis/app/views/rdas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rdas</h1>

<table class="table table-striped">
  <thead >
    <tr class="table-warning">
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rdas.each do |rda| %>
      <tr>
        <td><%= rda.nombre %></td>
        
        <td><%= link_to 'Mostrar', rda %></td>
        <td><%= link_to 'Editar', edit_rda_path(rda) %></td>
        <td><%= link_to 'Eliminar', rda, method: :delete, data: { confirm: 'Está seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rda', new_rda_path %>

tesis/app/views/rdas/new.html.erb
<h1>Nuevo resultado de aprendizaje</h1>

<%= render 'form', rda: @rda %>


<%= link_to 'volver', rdas_path %>

tesis/app/views/rdas/show.html.erb
<%# if !notice.nil? %>
	<div class="alert alert-success" id="notice"><%= notice %> </div>
<%#end%>

<h1> Resultado de aprendizaje </h1>

<p>
  <strong>Descripcion:</strong>
  <%= @rda.descripcion %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @rda.nombre %>
</p>

<%= link_to 'Edit', edit_rda_path(@rda) %> |
<%= link_to 'Back', rdas_path %>